"""Types for ``db_ops.transport.common_cli`` - GENERATED, do not edit.

One overload per ``common.cli`` command the reference describes, so ``run("run-sql", ...)`` is typed
as returning ``RunSqlAnswer`` and a key read from it that the answer does not carry is a type error.
Rendered by ``db_ops.lib.request_types.render_transport_stub``; held by
``tests/test_cli_types_match_the_reference.py``; written by ``control.cli request-types --write``.
The module itself is ``common_cli.py`` beside this file - a stub changes no behaviour.
"""

from typing import Any, Literal, overload

from db_ops.lib import cli_types as t
from db_ops.lib.common_cli import DEFAULT_MODULE as DEFAULT_MODULE
from db_ops.lib.common_cli import CommonCliError as CommonCliError
from db_ops.lib.common_cli import build_command as build_command
from db_ops.lib.common_cli import data_or_raise as data_or_raise
from db_ops.lib.common_cli import read_answer as read_answer
from db_ops.transport.process import ProcessResult as ProcessResult
from db_ops.transport.process import execute as execute


def spawn(command: str, request: dict[str, Any], *, module: str = ...,
          timeout_seconds: int | None = ...,
          stream_stderr: bool = ...) -> tuple[ProcessResult | None, str]: ...


@overload
def run(command: Literal['add-sql'], request: t.AddSqlRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RegistrationAnswer: ...

@overload
def run(command: Literal['app-command-set'], request: t.AppCommandSetRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ConfigEditAnswer: ...

@overload
def run(command: Literal['ask'], request: t.AskRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.AskAnswer: ...

@overload
def run(command: Literal['authorize'], request: t.AuthorizeRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['backup-chain'], request: t.BackupChainRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.BackupChainAnswer: ...

@overload
def run(command: Literal['backup-database'], request: t.BackupDatabaseRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.BackupDatabaseAnswer: ...

@overload
def run(command: Literal['build-showcase'], request: t.ShowcaseRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ShowcaseAnswer: ...

@overload
def run(command: Literal['check-credentials'], request: t.ConfigCheckRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.CheckCredentialsAnswer: ...

@overload
def run(command: Literal['check-identifiers'], request: t.IdentifierScanRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.IdentifierScanAnswer: ...

@overload
def run(command: Literal['check-objects'], request: t.ConfigCheckRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.CheckObjectsAnswer: ...

@overload
def run(command: Literal['check-references'], request: t.ConfigCheckRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.CheckReferencesAnswer: ...

@overload
def run(command: Literal['check-secret'], request: t.CheckSecretRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SecretCheckAnswer: ...

@overload
def run(command: Literal['check-secret-literals'], request: t.SecretLiteralsRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.IdentifierScanAnswer: ...

@overload
def run(command: Literal['copy-backup-dir'], request: t.CopyBackupDirRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.CopyBackupDirAnswer: ...

@overload
def run(command: Literal['copy-schema'], request: t.CopySchemaRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.CopySchemaAnswer: ...

@overload
def run(command: Literal['create-db-docker'], request: t.CreateDbDockerRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.CreateDbDockerAnswer: ...

@overload
def run(command: Literal['create-table-from-xlsx'], request: t.TableLoadRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.TableLoadAnswer: ...

@overload
def run(command: Literal['db-status'], request: t.DbStatusRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.DbStatusAnswer: ...

@overload
def run(command: Literal['delete-file'], request: t.FileDeleteRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.FileDeleteAnswer: ...

@overload
def run(command: Literal['delete-files'], request: t.FileDeleteRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.FileDeleteAnswer: ...

@overload
def run(command: Literal['describe-object'], request: t.DescribeObjectRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.DescribeObjectAnswer: ...

@overload
def run(command: Literal['disable-job'], request: t.SqlserverEmergencyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['due-check'], request: t.DueCheckRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.DueCheckAnswer: ...

@overload
def run(command: Literal['encrypt-secret'], request: t.EncryptSecretRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.EncryptSecretAnswer: ...

@overload
def run(command: Literal['export-data'], request: t.ExportDataRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ExportDataAnswer: ...

@overload
def run(command: Literal['fetch-file'], request: t.FileTransferRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.FileCopyAnswer: ...

@overload
def run(command: Literal['guide'], request: t.GuideRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GuideAnswer: ...

@overload
def run(command: Literal['host-facts'], request: t.HostOperationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['host-restart'], request: t.HostOperationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['host-service'], request: t.HostOperationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['import-data'], request: t.ImportDataRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ImportDataAnswer: ...

@overload
def run(command: Literal['init'], request: t.InitRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.InitAnswer: ...

@overload
def run(command: Literal['instance-add'], request: t.InstanceAddRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RegistrationAnswer: ...

@overload
def run(command: Literal['inventory-summary'], request: t.InventorySummaryRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.InventorySummaryAnswer: ...

@overload
def run(command: Literal['kill-spid'], request: t.SqlserverEmergencyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['lift-example'], request: t.ExampleLiftRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ExampleLiftAnswer: ...

@overload
def run(command: Literal['list-backup-files'], request: t.BackupFilesRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.BackupFileListAnswer: ...

@overload
def run(command: Literal['list-databases'], request: t.CatalogRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.DatabaseListAnswer: ...

@overload
def run(command: Literal['list-jobs'], request: t.CatalogRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.JobListAnswer: ...

@overload
def run(command: Literal['list-schemas'], request: t.CatalogRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SchemaListAnswer: ...

@overload
def run(command: Literal['list-targets'], request: t.ListingRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.TargetListAnswer: ...

@overload
def run(command: Literal['metric-batch'], request: t.MetricBatchRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.MetricBatchAnswer: ...

@overload
def run(command: Literal['metric-severity'], request: t.MetricSeverityRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ConfigEditAnswer: ...

@overload
def run(command: Literal['metric-toggle'], request: t.MetricToggleRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ConfigEditAnswer: ...

@overload
def run(command: Literal['move-db-docker'], request: t.MoveDbDockerRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.MoveDbDockerAnswer: ...

@overload
def run(command: Literal['pack-backup'], request: t.BackupPackRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.BackupPackAnswer: ...

@overload
def run(command: Literal['pack-files'], request: t.FileTransferRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.FilePackAnswer: ...

@overload
def run(command: Literal['probe-host'], request: t.ProbeHostRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ProbeHostAnswer: ...

@overload
def run(command: Literal['prune-backup-files'], request: t.BackupFilesRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.BackupPruneAnswer: ...

@overload
def run(command: Literal['prune-staged-backups'], request: t.PruneStagedBackupsRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.PruneStagedBackupsAnswer: ...

@overload
def run(command: Literal['pull-file'], request: t.BackupPackRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.FilePullPushAnswer: ...

@overload
def run(command: Literal['push-file'], request: t.BackupPackRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.FilePullPushAnswer: ...

@overload
def run(command: Literal['relay-file'], request: t.FileTransferRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.FileRelayAnswer: ...

@overload
def run(command: Literal['remote-credential-add'], request: t.RemoteCredentialAddRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RegistrationAnswer: ...

@overload
def run(command: Literal['restore-diff'], request: t.RestoreStepRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RestoreStepAnswer: ...

@overload
def run(command: Literal['restore-full'], request: t.RestoreStepRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RestoreStepAnswer: ...

@overload
def run(command: Literal['restore-key'], request: t.RestoreKeyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RestoreKeyAnswer: ...

@overload
def run(command: Literal['restore-log'], request: t.RestoreStepRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RestoreStepAnswer: ...

@overload
def run(command: Literal['restore-metadata'], request: t.RestoreMetadataRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RestoreMetadataAnswer: ...

@overload
def run(command: Literal['rotate-password'], request: t.RotatePasswordRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SecretCheckAnswer: ...

@overload
def run(command: Literal['run-cmd'], request: t.RunCmdRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RunCmdAnswer: ...

@overload
def run(command: Literal['run-sql'], request: t.RunSqlRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RunSqlAnswer: ...

@overload
def run(command: Literal['run-sqlcmd'], request: t.RunSqlcmdRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RunSqlcmdAnswer: ...

@overload
def run(command: Literal['secret-set'], request: t.SecretSetRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SecretSetAnswer: ...

@overload
def run(command: Literal['self-status'], request: t.SelfStatusRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SelfStatusAnswer: ...

@overload
def run(command: Literal['send-file'], request: t.FileTransferRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.FileCopyAnswer: ...

@overload
def run(command: Literal['shrink-log'], request: t.SqlserverEmergencyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['smb-credential'], request: t.SmbRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SmbCredentialAnswer: ...

@overload
def run(command: Literal['smb-delete'], request: t.SmbRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SmbDeleteAnswer: ...

@overload
def run(command: Literal['smb-get'], request: t.SmbRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SmbGetAnswer: ...

@overload
def run(command: Literal['smb-list'], request: t.SmbRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.SmbListAnswer: ...

@overload
def run(command: Literal['sql-command-add'], request: t.SqlCommandAddRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RegistrationAnswer: ...

@overload
def run(command: Literal['sql-target-add'], request: t.SqlTargetAddRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.RegistrationAnswer: ...

@overload
def run(command: Literal['sqlserver-apply-cu'], request: t.SqlserverPatchRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['sqlserver-export-instance'], request: t.SqlserverInstanceRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['sqlserver-precheck'], request: t.SqlserverPatchRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['sqlserver-replay-instance'], request: t.SqlserverInstanceRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['sqlserver-verify-build'], request: t.SqlserverPatchRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['sqlserver-verify-instance'], request: t.SqlserverInstanceRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['standardize-field-names'], request: t.ConfigMigrationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ConfigMigrationAnswer: ...

@overload
def run(command: Literal['start-job'], request: t.SqlserverEmergencyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.GateReportAnswer: ...

@overload
def run(command: Literal['trace-session'], request: t.TraceSessionRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.TraceSessionAnswer: ...

@overload
def run(command: Literal['upgrade-config'], request: t.ConfigMigrationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.ConfigMigrationAnswer: ...

@overload
def run(command: Literal['verify-restore'], request: t.VerifyRestoreRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> t.VerifyRestoreAnswer: ...

@overload
def run(command: str, request: dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> dict[str, Any]: ...

@overload
def run_allowing_failure(command: Literal['add-sql'], request: t.AddSqlRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RegistrationAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['app-command-set'], request: t.AppCommandSetRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ConfigEditAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['ask'], request: t.AskRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.AskAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['authorize'], request: t.AuthorizeRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['backup-chain'], request: t.BackupChainRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.BackupChainAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['backup-database'], request: t.BackupDatabaseRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.BackupDatabaseAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['build-showcase'], request: t.ShowcaseRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ShowcaseAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['check-credentials'], request: t.ConfigCheckRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.CheckCredentialsAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['check-identifiers'], request: t.IdentifierScanRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.IdentifierScanAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['check-objects'], request: t.ConfigCheckRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.CheckObjectsAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['check-references'], request: t.ConfigCheckRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.CheckReferencesAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['check-secret'], request: t.CheckSecretRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SecretCheckAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['check-secret-literals'], request: t.SecretLiteralsRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.IdentifierScanAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['copy-backup-dir'], request: t.CopyBackupDirRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.CopyBackupDirAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['copy-schema'], request: t.CopySchemaRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.CopySchemaAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['create-db-docker'], request: t.CreateDbDockerRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.CreateDbDockerAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['create-table-from-xlsx'], request: t.TableLoadRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.TableLoadAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['db-status'], request: t.DbStatusRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.DbStatusAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['delete-file'], request: t.FileDeleteRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.FileDeleteAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['delete-files'], request: t.FileDeleteRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.FileDeleteAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['describe-object'], request: t.DescribeObjectRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.DescribeObjectAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['disable-job'], request: t.SqlserverEmergencyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['due-check'], request: t.DueCheckRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.DueCheckAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['encrypt-secret'], request: t.EncryptSecretRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.EncryptSecretAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['export-data'], request: t.ExportDataRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ExportDataAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['fetch-file'], request: t.FileTransferRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.FileCopyAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['guide'], request: t.GuideRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GuideAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['host-facts'], request: t.HostOperationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['host-restart'], request: t.HostOperationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['host-service'], request: t.HostOperationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['import-data'], request: t.ImportDataRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ImportDataAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['init'], request: t.InitRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.InitAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['instance-add'], request: t.InstanceAddRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RegistrationAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['inventory-summary'], request: t.InventorySummaryRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.InventorySummaryAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['kill-spid'], request: t.SqlserverEmergencyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['lift-example'], request: t.ExampleLiftRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ExampleLiftAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['list-backup-files'], request: t.BackupFilesRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.BackupFileListAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['list-databases'], request: t.CatalogRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.DatabaseListAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['list-jobs'], request: t.CatalogRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.JobListAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['list-schemas'], request: t.CatalogRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SchemaListAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['list-targets'], request: t.ListingRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.TargetListAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['metric-batch'], request: t.MetricBatchRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.MetricBatchAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['metric-severity'], request: t.MetricSeverityRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ConfigEditAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['metric-toggle'], request: t.MetricToggleRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ConfigEditAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['move-db-docker'], request: t.MoveDbDockerRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.MoveDbDockerAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['pack-backup'], request: t.BackupPackRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.BackupPackAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['pack-files'], request: t.FileTransferRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.FilePackAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['probe-host'], request: t.ProbeHostRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ProbeHostAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['prune-backup-files'], request: t.BackupFilesRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.BackupPruneAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['prune-staged-backups'], request: t.PruneStagedBackupsRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.PruneStagedBackupsAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['pull-file'], request: t.BackupPackRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.FilePullPushAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['push-file'], request: t.BackupPackRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.FilePullPushAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['relay-file'], request: t.FileTransferRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.FileRelayAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['remote-credential-add'], request: t.RemoteCredentialAddRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RegistrationAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['restore-diff'], request: t.RestoreStepRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RestoreStepAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['restore-full'], request: t.RestoreStepRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RestoreStepAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['restore-key'], request: t.RestoreKeyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RestoreKeyAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['restore-log'], request: t.RestoreStepRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RestoreStepAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['restore-metadata'], request: t.RestoreMetadataRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RestoreMetadataAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['rotate-password'], request: t.RotatePasswordRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SecretCheckAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['run-cmd'], request: t.RunCmdRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RunCmdAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['run-sql'], request: t.RunSqlRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RunSqlAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['run-sqlcmd'], request: t.RunSqlcmdRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RunSqlcmdAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['secret-set'], request: t.SecretSetRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SecretSetAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['self-status'], request: t.SelfStatusRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SelfStatusAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['send-file'], request: t.FileTransferRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.FileCopyAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['shrink-log'], request: t.SqlserverEmergencyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['smb-credential'], request: t.SmbRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SmbCredentialAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['smb-delete'], request: t.SmbRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SmbDeleteAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['smb-get'], request: t.SmbRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SmbGetAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['smb-list'], request: t.SmbRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.SmbListAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['sql-command-add'], request: t.SqlCommandAddRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RegistrationAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['sql-target-add'], request: t.SqlTargetAddRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.RegistrationAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['sqlserver-apply-cu'], request: t.SqlserverPatchRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['sqlserver-export-instance'], request: t.SqlserverInstanceRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['sqlserver-precheck'], request: t.SqlserverPatchRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['sqlserver-replay-instance'], request: t.SqlserverInstanceRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['sqlserver-verify-build'], request: t.SqlserverPatchRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['sqlserver-verify-instance'], request: t.SqlserverInstanceRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['standardize-field-names'], request: t.ConfigMigrationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ConfigMigrationAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['start-job'], request: t.SqlserverEmergencyRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.GateReportAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['trace-session'], request: t.TraceSessionRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.TraceSessionAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['upgrade-config'], request: t.ConfigMigrationRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.ConfigMigrationAnswer, str]: ...

@overload
def run_allowing_failure(command: Literal['verify-restore'], request: t.VerifyRestoreRequest | dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, t.VerifyRestoreAnswer, str]: ...

@overload
def run_allowing_failure(command: str, request: dict[str, Any], *, timeout_seconds: int | None = ..., stream_stderr: bool = ...) -> tuple[bool, dict[str, Any], str]: ...
