all:
  children:
    sqlserver:
      vars:
        ansible_user: tuser
      hosts:
        sql-01:
          ansible_host: 192.168.18.31
          mssql_role: primary
        sql-02:
          ansible_host: 192.168.18.32
          mssql_role: secondary
        sql-03:
          ansible_host: 192.168.18.33
          mssql_role: secondary
