<#
.SYNOPSIS
    Build the db_ops Docker image on Windows and assemble a deploy bundle for Ubuntu.

.DESCRIPTION
    Runs from tools/db_ops. Produces:
        deploy/db_ops_deploy/db_ops_image.tar   - the exported image
        deploy/db_ops_deploy/docker-compose.yml - runtime compose (no build)
        deploy/db_ops_deploy/config.json, data/, sql/, logs/, runtime/

    Secrets travel ENCRYPTED inside data/encrypted_secret_text.json (generated by
    scripts/python/encrypt_secret_text.py). The decryption passphrase is NOT in
    the bundle; you supply it at runtime with --key.

    Copy the whole deploy/db_ops_deploy folder to the Ubuntu host, then:
        docker load -i db_ops_image.tar
        docker compose run -d --name db_ops_daemon db_ops daemon --key "<passphrase>"

.NOTES
    The image version is read from db_ops/__init__.py (__version__) — the single
    source of truth. The image is tagged db_ops:<version> AND db_ops:latest and
    carries org.opencontainers.image.version=<version> as a label. Bump
    __version__ on every fix; the next build picks it up automatically.

.EXAMPLE
    .\docker\build_and_package.ps1
#>
[CmdletBinding()]
param()

# NOTE: Continue (not Stop). Docker writes build progress to stderr; under
# Windows PowerShell 5.1, $ErrorActionPreference="Stop" turns the first stderr
# line into a terminating error and aborts the build. We invoke docker through
# cmd.exe (keeps stderr as plain text) and gate on $LASTEXITCODE instead.
$ErrorActionPreference = "Continue"

# Always operate from the tools/db_ops directory (parent of this script's folder).
$toolDir = Split-Path -Parent $PSScriptRoot
Set-Location $toolDir
Write-Host "Working dir: $toolDir" -ForegroundColor Cyan

# Version is the single source of truth in db_ops/__init__.py (__version__).
$initPy = Join-Path $toolDir "db_ops\__init__.py"
$verMatch = Select-String -Path $initPy -Pattern '__version__\s*=\s*"([^"]+)"'
if (-not $verMatch) { throw "Could not read __version__ from $initPy" }
$version = $verMatch.Matches[0].Groups[1].Value
$versionTag = "db_ops:$version"
$latestTag = "db_ops:latest"
Write-Host "Version: $version  (image tags: $versionTag, $latestTag)" -ForegroundColor Cyan

# 0. Sanity: Docker present?
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "Docker not found. Install Docker Desktop for Windows and start it first."
}

$bundle = Join-Path $toolDir "deploy\db_ops_deploy"
if (Test-Path $bundle) { Remove-Item $bundle -Recurse -Force }
New-Item -ItemType Directory -Path $bundle -Force | Out-Null

# 1. Build the linux/amd64 image (matches a typical Ubuntu server).
Write-Host "`n[1/4] Building image $versionTag (linux/amd64)..." -ForegroundColor Green
cmd.exe /c "docker build --platform linux/amd64 --label org.opencontainers.image.version=$version -t $versionTag -t $latestTag ."
if ($LASTEXITCODE -ne 0) { throw "docker build failed." }

# 2. Export the image to a tar (both tags travel in the tar so `docker load`
#    restores db_ops:<version> and db_ops:latest).
Write-Host "`n[2/4] Exporting image to tar..." -ForegroundColor Green
$tarPath = Join-Path $bundle "db_ops_image.tar"
cmd.exe /c "docker save $versionTag $latestTag -o `"$tarPath`""
if ($LASTEXITCODE -ne 0) { throw "docker save failed." }

# 3. Assemble runtime inputs.
Write-Host "`n[3/4] Assembling deploy bundle..." -ForegroundColor Green

# The encrypted secret file must exist; the daemon cannot decrypt without it.
if (-not (Test-Path "data\encrypted_secret_text.json")) {
    throw "data\encrypted_secret_text.json not found. Run: python scripts\python\encrypt_secret_text.py --key `"<passphrase>`""
}

Copy-Item "docker-compose.runtime.yml" (Join-Path $bundle "docker-compose.yml") -Force
Copy-Item "config.json" $bundle -Force
Copy-Item "data" $bundle -Recurse -Force
Copy-Item "sql"  $bundle -Recurse -Force
New-Item -ItemType Directory -Path (Join-Path $bundle "logs")    -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $bundle "runtime") -Force | Out-Null
Write-Host "  Encrypted secrets included via data\encrypted_secret_text.json (passphrase supplied at runtime with --key)." -ForegroundColor Yellow

# Strip pyc/cache noise that Copy-Item may have pulled in.
Get-ChildItem $bundle -Recurse -Directory -Filter "__pycache__" -ErrorAction SilentlyContinue |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

# Verify the bundle has the essentials (EAP=Continue would not have stopped on a
# failed Copy-Item above).
foreach ($must in @("db_ops_image.tar", "docker-compose.yml", "config.json", "data\encrypted_secret_text.json", "sql")) {
    if (-not (Test-Path (Join-Path $bundle $must))) { throw "Deploy bundle is missing: $must" }
}

# 4. Done.
$tarSize = "{0:N0} MB" -f ((Get-Item (Join-Path $bundle "db_ops_image.tar")).Length / 1MB)
Write-Host "`n[4/4] Done." -ForegroundColor Green
Write-Host "  Version: $version"
Write-Host "  Bundle : $bundle"
Write-Host "  Image  : db_ops_image.tar ($tarSize)  [tags: $versionTag, $latestTag]"
Write-Host "`nNext: copy the bundle to Ubuntu, then run:" -ForegroundColor Cyan
Write-Host "  docker load -i db_ops_image.tar"
Write-Host '  docker compose run -d --name db_ops_daemon db_ops daemon --key "<passphrase>"'
Write-Host "  docker compose logs -f db_ops_daemon"
