all:
  children:
    mysql:
      vars:
        ansible_user: tuser
      hosts:
        mysql-01:
          ansible_host: 192.168.18.11
          mysql_role: primary
        mysql-02:
          ansible_host: 192.168.18.12
          mysql_role: replica
        mysql-03:
          ansible_host: 192.168.18.13
          mysql_role: replica
