"""Build the on-disk plan for a lab database instance from a validated spec.

This module is pure: given a :class:`DockerDbSpec` (and a resolved password
value) it returns the exact files to write and the commands to run, with no side
effects. The provisioner consumes the plan for real runs; ``--dry-run`` prints it.
Keeping generation side-effect-free is what lets dry-run and real runs share one
code path.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from db_ops.sre.docker_db import templates
from db_ops.sre.docker_db.models import DockerDbSpec

MASKED_PASSWORD = "***"


@dataclass(frozen=True)
class PlannedFile:
    relpath: str          # path relative to the instance directory
    content: str
    secret: bool = False  # True when the file contains the real password


@dataclass(frozen=True)
class ProvisionPlan:
    spec: DockerDbSpec
    instance_dir: str
    compose_path: str
    files: list[PlannedFile]
    data_dirs: list[str] = field(default_factory=list)
    services: list[str] = field(default_factory=list)
    connection: dict = field(default_factory=dict)

    @property
    def up_command(self) -> list[str]:
        # `docker compose up -d` from the instance directory; --env-file makes the
        # DB_PASSWORD available for interpolation regardless of CWD.
        return ["docker", "compose", "--env-file", ".env", "up", "-d"]


def _env_file_content(spec: DockerDbSpec, password: str) -> str:
    lines = [
        "# Generated by db_ops.sre.create-db-docker. Contains the DB password -",
        "# keep it out of version control (compose reads DB_PASSWORD from here).",
        f"DB_PASSWORD={password}",
        f"DB_ENGINE={spec.engine}",
        f"DB_VERSION={spec.version}",
        f"HOST_PORT={spec.host_port}",
    ]
    return "\n".join(lines) + "\n"


def _connection_info(spec: DockerDbSpec, *, worker_host: str, compose_path: str) -> dict:
    meta = spec.meta
    connect = meta.connect_template.format(
        host=worker_host or "<worker-host-or-ip>",
        port=spec.host_port,
        username=meta.username,
        database=meta.database,
    )
    return {
        "engine": spec.engine,
        "version": spec.version,
        "mode": spec.mode,
        "host": worker_host or "<worker-host-or-ip>",
        "port": spec.host_port,
        "username": meta.username,
        "database": meta.database,
        "password_source": f"env:{spec.password_env}",
        "compose_path": compose_path,
        "connect": connect,
    }


def build_plan(
    spec: DockerDbSpec,
    *,
    containers_dir: str,
    password: str | None,
    worker_host: str = "",
    dry_run: bool = False,
) -> ProvisionPlan:
    """Return the full provisioning plan for ``spec``.

    ``password`` is the resolved secret value; for ``dry_run`` pass ``None`` and
    the ``.env`` file is rendered with a masked placeholder so nothing sensitive
    is ever printed.
    """
    instance_dir = f"{containers_dir.rstrip('/')}/{spec.name}"
    compose_path = f"{instance_dir}/docker-compose.yml"

    ctx = templates.build_context(spec)
    compose_yaml = templates.render(templates.load_template(spec.engine, spec.mode), ctx)

    env_value = MASKED_PASSWORD if (dry_run or password is None) else password
    env_content = _env_file_content(spec, env_value)

    files = [
        PlannedFile("docker-compose.yml", compose_yaml),
        PlannedFile(".env", env_content, secret=not (dry_run or password is None)),
    ]
    # Engine/mode-specific support files (e.g. the PostgreSQL HA init script).
    for relpath, content in templates.extra_files(spec):
        files.append(PlannedFile(relpath, content))

    # Database data lives in Docker-managed named volumes (declared in the compose
    # file), so no host data directories are pre-created — a host bind mount would
    # inherit the host uid and break the DB image's own user (permission errors).
    data_dirs: list[str] = []

    return ProvisionPlan(
        spec=spec,
        instance_dir=instance_dir,
        compose_path=compose_path,
        files=files,
        data_dirs=data_dirs,
        services=spec.node_names(),
        connection=_connection_info(spec, worker_host=worker_host, compose_path=compose_path),
    )
