"""Locate and render the docker-compose templates for lab database instances.

The project does not depend on Jinja2, so this module ships a tiny, well-tested
renderer that supports exactly the two constructs the templates need:

* ``{{ dotted.path }}``            - scalar substitution against the context
* ``{% for x in items %}..{% endfor %}`` - single-level iteration over a list

That keeps the ``.j2`` files under ``tools/db_ops/templates/docker`` the single
source of truth for the generated compose files (no compose YAML is hand-built
in Python) while avoiding a new runtime dependency.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from db_ops.sre.docker_db.models import DockerDbSpec

# The .j2 templates ship *inside* the package (db_ops/sre/docker_db/templates/docker)
# so they travel with `COPY db_ops ./db_ops` into the worker image — a sibling
# tools/db_ops/templates dir would NOT be in the image or the deploy bundle.
TEMPLATES_DIR = Path(__file__).resolve().parent / "templates" / "docker"

_VAR_RE = re.compile(r"{{\s*([A-Za-z0-9_.]+)\s*}}")
_FOR_RE = re.compile(
    r"{%\s*for\s+(\w+)\s+in\s+([A-Za-z0-9_.]+)\s*%}(.*?){%\s*endfor\s*%}",
    re.DOTALL,
)


def _resolve(path: str, ctx: dict[str, Any]) -> Any:
    cur: Any = ctx
    for part in path.split("."):
        if isinstance(cur, dict):
            cur = cur.get(part)
        else:
            cur = getattr(cur, part, None)
        if cur is None:
            return None
    return cur


def _render_scalars(text: str, ctx: dict[str, Any]) -> str:
    def _sub(match: re.Match[str]) -> str:
        value = _resolve(match.group(1), ctx)
        return "" if value is None else str(value)

    return _VAR_RE.sub(_sub, text)


def render(template_text: str, ctx: dict[str, Any]) -> str:
    """Render ``template_text`` with ``ctx``. Loops are expanded first (each
    iteration sees the loop variable plus a ``loop`` helper), then scalars."""

    def _expand_for(match: re.Match[str]) -> str:
        var, list_path, body = match.group(1), match.group(2), match.group(3)
        items = _resolve(list_path, ctx) or []
        chunks: list[str] = []
        total = len(items)
        for index, item in enumerate(items):
            loop = {
                "index": index + 1,
                "index0": index,
                "first": index == 0,
                "last": index == total - 1,
            }
            chunks.append(_render_scalars(body, {**ctx, var: item, "loop": loop}))
        return "".join(chunks)

    expanded = _FOR_RE.sub(_expand_for, template_text)
    return _render_scalars(expanded, ctx)


# Provisioned on the PostgreSQL HA primary via /docker-entrypoint-initdb.d (runs
# once on first init). Creates the replication role and opens pg_hba for standbys.
# This is a plain file mounted into the container — NOT processed by compose — so
# it uses normal $VAR / $$ dollar-quoting, provided by the postgres image at runtime.
POSTGRES_HA_INITDB = r"""#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'replicator') THEN
    CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD '$POSTGRES_PASSWORD';
  END IF;
END
\$\$;
EOSQL

cat >> "$PGDATA/pg_hba.conf" <<'EOF'
host    replication    replicator    0.0.0.0/0    scram-sha-256
host    replication    replicator    ::/0         scram-sha-256
EOF
"""


# Creates the availability group once the nodes are healthy. It cannot be an image init hook
# (SQL Server has none) and it cannot be compose (the steps span containers and must happen in
# order), so the provisioner runs this script after the health check, from wherever it runs —
# it only needs the docker CLI and the socket, both of which the provisioner already uses.
#
# CLUSTER_TYPE = NONE: no WSFC/Pacemaker in a container lab, so the AG is read-scale — manual
# failover, no listener (see the compose header).
#
# All replicas share ONE certificate, which is what the SQL Server on Linux AG tutorial does:
# the mirroring endpoint authenticates with that certificate, so a node presenting it is
# trusted. Per-node certificates would need cross-imported logins for no benefit here.
MSSQL_AG_SETUP = r"""#!/bin/bash
# Generated by db_ops.sre.create-db-docker - Always On AG bootstrap (CLUSTER_TYPE=NONE).
set -euo pipefail

AG_NAME="{{ ag_name }}"
AG_DATABASE="{{ ag_database }}"
PRIMARY="{{ primary_node }}"
NODES=({{ node_list }})
SECONDARIES=({{ secondary_list }})
ENDPOINT_PORT=5022

# The password is never handled by this script. sqlcmd reads it from the container's own
# MSSQL_SA_PASSWORD (compose put it there from .env), both to log in and, via sqlcmd's
# $(VAR) substitution, wherever the SQL needs it — so it appears in no argv and no log line.
#
# The SQL is piped in on stdin rather than passed with -Q: through `docker exec bash -lc` a
# -Q argument would be re-expanded by the inner shell, and a $(...) inside the SQL would be
# run as a command instead of reaching sqlcmd.

# mssql-tools18 (2022+) needs -C to trust the self-signed cert; older images ship tools17.
sqlcmd_path() {
  if docker exec "$1" test -x /opt/mssql-tools18/bin/sqlcmd 2>/dev/null; then
    echo "/opt/mssql-tools18/bin/sqlcmd -C"
  else
    echo "/opt/mssql-tools/bin/sqlcmd"
  fi
}

run_sql() {  # run_sql <container> <sql>
  local node="$1" sql="$2" tool
  tool="$(sqlcmd_path "$node")"
  printf '%s\nGO\n' "$sql" | docker exec -i "$node" bash -lc \
    "$tool -S localhost -U sa -P \"\$MSSQL_SA_PASSWORD\" -b -h -1 -W"
}

wait_sql() {  # a restarted node needs to accept connections again before we go on
  local node="$1" i
  for i in $(seq 1 60); do
    if run_sql "$node" "SELECT 1" >/dev/null 2>&1; then return 0; fi
    sleep 5
  done
  echo "ERROR: $node did not accept connections after restart." >&2
  return 1
}

# 1. Always On must be enabled in the engine. MSSQL_ENABLE_HADR=1 does it at startup; if the
#    image ignored it, set it the supported way and restart, rather than failing later with a
#    cryptic "Always On is not enabled" from CREATE AVAILABILITY GROUP.
for node in "${NODES[@]}"; do
  enabled="$(run_sql "$node" "SELECT CAST(SERVERPROPERTY('IsHadrEnabled') AS INT)" | tr -d '[:space:]')"
  if [ "$enabled" != "1" ]; then
    echo "Enabling Always On on $node ..."
    docker exec "$node" /opt/mssql/bin/mssql-conf set hadr.hadrenabled 1
    docker restart "$node" >/dev/null
    wait_sql "$node"
  fi
done

# 2. One certificate, created on the primary, imported by every secondary; mirroring endpoints
#    on 5022 authenticate with it.
echo "Creating the mirroring certificate on $PRIMARY ..."
run_sql "$PRIMARY" "
IF NOT EXISTS (SELECT 1 FROM sys.symmetric_keys WHERE name = '##MS_DatabaseMasterKey##')
    CREATE MASTER KEY ENCRYPTION BY PASSWORD = '\$(MSSQL_SA_PASSWORD)';
IF NOT EXISTS (SELECT 1 FROM sys.certificates WHERE name = 'dbm_certificate')
    CREATE CERTIFICATE dbm_certificate WITH SUBJECT = 'dbm';
" > /dev/null

docker exec "$PRIMARY" bash -lc "rm -f /var/opt/mssql/data/dbm_certificate.*"
run_sql "$PRIMARY" "
BACKUP CERTIFICATE dbm_certificate
  TO FILE = '/var/opt/mssql/data/dbm_certificate.cer'
  WITH PRIVATE KEY (FILE = '/var/opt/mssql/data/dbm_certificate.pvk',
                    ENCRYPTION BY PASSWORD = '\$(MSSQL_SA_PASSWORD)');
" > /dev/null

tmp="$(mktemp -d)"
docker cp "$PRIMARY:/var/opt/mssql/data/dbm_certificate.cer" "$tmp/"
docker cp "$PRIMARY:/var/opt/mssql/data/dbm_certificate.pvk" "$tmp/"

for node in "${SECONDARIES[@]}"; do
  echo "Importing the certificate into $node ..."
  docker cp "$tmp/dbm_certificate.cer" "$node:/var/opt/mssql/data/"
  docker cp "$tmp/dbm_certificate.pvk" "$node:/var/opt/mssql/data/"
  # docker cp lands the files as root; the engine runs as mssql and could not read them. The
  # container's own user cannot chown (it is not root), so the exec has to ask for uid 0.
  docker exec -u 0 "$node" chown mssql:root \
    /var/opt/mssql/data/dbm_certificate.cer /var/opt/mssql/data/dbm_certificate.pvk
  docker exec -u 0 "$node" chmod 640 \
    /var/opt/mssql/data/dbm_certificate.cer /var/opt/mssql/data/dbm_certificate.pvk
  run_sql "$node" "
IF NOT EXISTS (SELECT 1 FROM sys.symmetric_keys WHERE name = '##MS_DatabaseMasterKey##')
    CREATE MASTER KEY ENCRYPTION BY PASSWORD = '\$(MSSQL_SA_PASSWORD)';
IF NOT EXISTS (SELECT 1 FROM sys.certificates WHERE name = 'dbm_certificate')
    CREATE CERTIFICATE dbm_certificate
      FROM FILE = '/var/opt/mssql/data/dbm_certificate.cer'
      WITH PRIVATE KEY (FILE = '/var/opt/mssql/data/dbm_certificate.pvk',
                        DECRYPTION BY PASSWORD = '\$(MSSQL_SA_PASSWORD)');
  " > /dev/null
done
rm -rf "$tmp"

for node in "${NODES[@]}"; do
  echo "Starting the mirroring endpoint on $node ..."
  run_sql "$node" "
IF NOT EXISTS (SELECT 1 FROM sys.endpoints WHERE name = 'hadr_endpoint')
    CREATE ENDPOINT hadr_endpoint
      AS TCP (LISTENER_PORT = $ENDPOINT_PORT)
      FOR DATABASE_MIRRORING (ROLE = ALL,
                              AUTHENTICATION = CERTIFICATE dbm_certificate,
                              ENCRYPTION = REQUIRED ALGORITHM AES);
ALTER ENDPOINT hadr_endpoint STATE = STARTED;
ALTER EVENT SESSION AlwaysOn_health ON SERVER WITH (STARTUP_STATE = ON);
  " > /dev/null
done

# 3. The availability group. SEEDING_MODE = AUTOMATIC means the secondaries are seeded by SQL
#    Server itself — no backup/restore dance — which is why every replica must be granted
#    CREATE ANY DATABASE.
echo "Creating availability group $AG_NAME ..."
replicas=""
for node in "${NODES[@]}"; do
  [ -z "$replicas" ] || replicas="$replicas,"
  replicas="$replicas
  N'$node' WITH (
    ENDPOINT_URL = N'tcp://$node:$ENDPOINT_PORT',
    AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
    FAILOVER_MODE = MANUAL,
    SEEDING_MODE = AUTOMATIC)"
done

run_sql "$PRIMARY" "
IF NOT EXISTS (SELECT 1 FROM sys.availability_groups WHERE name = '$AG_NAME')
    CREATE AVAILABILITY GROUP [$AG_NAME]
      WITH (CLUSTER_TYPE = NONE)
      FOR REPLICA ON $replicas;
ALTER AVAILABILITY GROUP [$AG_NAME] GRANT CREATE ANY DATABASE;
" > /dev/null

for node in "${SECONDARIES[@]}"; do
  echo "Joining $node to $AG_NAME ..."
  run_sql "$node" "
IF NOT EXISTS (SELECT 1 FROM sys.availability_groups WHERE name = '$AG_NAME')
    ALTER AVAILABILITY GROUP [$AG_NAME] JOIN WITH (CLUSTER_TYPE = NONE);
ALTER AVAILABILITY GROUP [$AG_NAME] GRANT CREATE ANY DATABASE;
  " > /dev/null
done

# 4. A database in the group, so the lab replicates something from the first minute. Automatic
#    seeding needs FULL recovery and one full backup to start the log chain.
echo "Adding database $AG_DATABASE to $AG_NAME ..."
run_sql "$PRIMARY" "
IF DB_ID('$AG_DATABASE') IS NULL CREATE DATABASE [$AG_DATABASE];
ALTER DATABASE [$AG_DATABASE] SET RECOVERY FULL;
IF NOT EXISTS (SELECT 1 FROM msdb.dbo.backupset WHERE database_name = '$AG_DATABASE' AND type = 'D')
    BACKUP DATABASE [$AG_DATABASE] TO DISK = '/var/opt/mssql/data/$AG_DATABASE.bak' WITH INIT;
IF NOT EXISTS (SELECT 1 FROM sys.availability_databases_cluster WHERE database_name = '$AG_DATABASE')
    ALTER AVAILABILITY GROUP [$AG_NAME] ADD DATABASE [$AG_DATABASE];
" > /dev/null

echo
echo "Availability group $AG_NAME:"
run_sql "$PRIMARY" "
SELECT r.replica_server_name, rs.role_desc, rs.synchronization_health_desc, rs.connected_state_desc
FROM sys.dm_hadr_availability_replica_states rs
JOIN sys.availability_replicas r ON r.replica_id = rs.replica_id
ORDER BY rs.role_desc DESC;"
echo
echo "Failover is MANUAL (CLUSTER_TYPE = NONE): on the target replica run"
echo "  ALTER AVAILABILITY GROUP [$AG_NAME] FAILOVER;                          -- planned, primary alive"
echo "  ALTER AVAILABILITY GROUP [$AG_NAME] FORCE_FAILOVER_ALLOW_DATA_LOSS;    -- primary gone"
"""


# Ships archived redo logs primary -> standby, Standard-Edition style: Oracle Free blocks
# every remote redo transport mode with ORA-00439 (ASYNC, SYNC and FAL gap fetch alike —
# verified empirically on 23.26.2), so the <name>-shipper sidecar forces a log switch and
# copies + registers each new archived log; the standby's managed recovery applies it.
ORACLE_DG_SHIP_LOOP = r"""#!/bin/sh
# Generated by db_ops.sre.create-db-docker - Data Guard lab log shipper.
#
# Oracle Free gates the WHOLE Managed Standby feature behind ORA-00439 (remote transport,
# FAL, and even REGISTER PHYSICAL LOGFILE — all verified on 23.26.2). Plain media recovery
# is NOT gated, so this ships each archived log under the name RECOVER expects
# (log_archive_format with %t/%s/%r filled in) into one incoming dir and runs
#   ALTER DATABASE RECOVER AUTOMATIC FROM '<dir>' STANDBY DATABASE
# per cycle — the classic Standard-Edition DIY standby. ONESHOT=1 runs one cycle (the
# setup script uses it); otherwise it loops forever every INTERVAL seconds.
: "${PRIMARY:?}" "${STANDBY:?}"
INTERVAL="${INTERVAL:-120}"
INCOMING=/opt/oracle/oradata/fra/incoming

sqlp() { printf '%s\n' "$1" | docker exec -i "$PRIMARY" bash -c 'sqlplus -S / as sysdba'; }
sqls() { printf '%s\n' "$1" | docker exec -i "$STANDBY" bash -c 'sqlplus -S / as sysdba'; }

RLID=$(sqls "set heading off feedback off
SELECT resetlogs_id FROM v\$database_incarnation WHERE status='CURRENT';" | tr -d '[:space:]')
FMT=$(sqls "set heading off feedback off
SELECT value FROM v\$parameter WHERE name='log_archive_format';" | tr -d '[:space:]')
[ -n "$FMT" ] || FMT='%t_%s_%r.dbf'

# Both values are sqlplus OUTPUT, so a restarted or mounted-but-not-open database answers with an
# ORA- banner instead of a number. Feeding that into the name template produced an empty filename
# and the sidecar then ran `cat > '<incoming>/'` against the directory itself, logging
# "Is a directory" every cycle while shipping nothing -- silently, for 12 days, on 2026-07-20.
# Validate before use: a resetlogs_id is digits, and a usable format must carry the sequence.
case "$RLID" in
  ''|*[!0-9]*)
    echo "shipper: refusing to ship - resetlogs_id is not numeric: '$RLID'" >&2
    RLID='' ;;
esac
case "$FMT" in
  *%s*) ;;
  *) echo "shipper: refusing to ship - log_archive_format has no %s: '$FMT'" >&2
     FMT='' ;;
esac

ship_cycle() {
  # No usable name template means every destination path would collapse to the incoming directory.
  # Stop the cycle instead: a shipper that ships nothing must say so, not log a filesystem error.
  if [ -z "$RLID" ] || [ -z "$FMT" ]; then
    echo "shipper: skipping cycle - no valid RLID/FMT (standby will fall behind)" >&2
    return 1
  fi
  sqlp "ALTER SYSTEM ARCHIVE LOG CURRENT;" >/dev/null 2>&1
  docker exec "$STANDBY" mkdir -p "$INCOMING" >/dev/null 2>&1
  new=0
  for f in $(docker exec "$PRIMARY" bash -c 'find /opt/oracle/oradata/fra -type f -name "*.arc" | sort' 2>/dev/null); do
    base=$(basename "$f")                     # OMF: o1_mf_<thread>_<seq>_<uniq>_.arc
    t=$(echo "$base" | cut -d_ -f3)
    s=$(echo "$base" | cut -d_ -f4)
    # awk -v, not sed s///: these values are interpolated INTO the expression, and a single '/'
    # anywhere in them makes sed exit with "bad option in substitution expression", leaving $dest
    # empty. awk takes them as data, so no character in a value can change the substitution.
    dest=$(printf '%s' "$FMT" | awk -v t="$t" -v s="$s" -v r="$RLID" \
             '{gsub(/%t/,t); gsub(/%s/,s); gsub(/%r/,r); print}')
    case "$dest" in
      ''|*/) echo "shipper: computed an unusable destination for $base (fmt='$FMT')" >&2
             continue ;;
    esac
    docker exec "$STANDBY" test -f "$INCOMING/$dest" >/dev/null 2>&1 && continue
    docker exec "$PRIMARY" cat "$f" | docker exec -i "$STANDBY" sh -c "cat > '$INCOMING/$dest'"
    new=1
  done
  if [ "$new" = "1" ]; then
    # Applies every available log, then errors when the next one is not shipped yet —
    # that is the expected loop exit, not a failure. CANCEL clears any leftover session.
    sqls "ALTER DATABASE RECOVER AUTOMATIC FROM '$INCOMING' STANDBY DATABASE;" >/dev/null 2>&1
    sqls "ALTER DATABASE RECOVER CANCEL;" >/dev/null 2>&1
  fi
}

if [ "${ONESHOT:-0}" = "1" ]; then
  ship_cycle
  exit 0
fi
while true; do
  ship_cycle
  sleep "$INTERVAL"
done
"""


# Converts <name>-standby-1 into a physical standby of <name>-primary and starts managed
# recovery — Oracle Data Guard 1/1 on gvenzl/oracle-free (Free supports Data Guard since
# 23ai). Like the SQL Server AG script, it cannot be compose or an image init hook: the
# steps span both containers and must run in order once each is healthy, so the provisioner
# runs it afterwards from the instance dir (it only needs the docker CLI).
#
# The password is never on any argv: every remote connect string is built INSIDE the
# container from its own ORACLE_PASSWORD env (single-quoted through `docker exec bash -c`),
# and local connects use OS authentication (`/ as sysdba`).
ORACLE_DG_SETUP = r"""#!/bin/bash
# Generated by db_ops.sre.create-db-docker - Oracle Data Guard 1/1 bootstrap.
set -euo pipefail

PRIMARY="{{ primary_node }}"
STANDBY="{{ standby_node }}"
DB_NAME="FREE"                 # gvenzl/oracle-free SID/db_name
SB_UNIQUE="FREE_SB"            # standby db_unique_name (db_name stays FREE)
PDB="FREEPDB1"
FRA_SIZE="10G"

sql() {  # sql <container> <sql...>   (OS-auth sysdba inside the container)
  local node="$1"; shift
  printf '%s\n' "$@" | docker exec -i "$node" bash -c \
    'sqlplus -S -L / as sysdba' | sed '/^$/d'
}

echo "== 1. Primary: FORCE LOGGING + ARCHIVELOG + FRA =="
docker exec "$PRIMARY" mkdir -p /opt/oracle/oradata/fra
sql "$PRIMARY" "
whenever sqlerror exit failure
ALTER SYSTEM SET db_recovery_file_dest_size=$FRA_SIZE SCOPE=BOTH;
ALTER SYSTEM SET db_recovery_file_dest='/opt/oracle/oradata/fra' SCOPE=BOTH;
exit"
# FORCE LOGGING only when it is off — a second ALTER raises ORA-12920 (already in that mode),
# which would abort this idempotent script. PL/SQL block so a no-op stays a no-op.
sql "$PRIMARY" "
whenever sqlerror exit failure
BEGIN
  FOR r IN (SELECT force_logging FROM v\$database) LOOP
    IF r.force_logging <> 'YES' THEN EXECUTE IMMEDIATE 'ALTER DATABASE FORCE LOGGING'; END IF;
  END LOOP;
END;
/
exit"
archivelog="$(sql "$PRIMARY" "SELECT log_mode FROM v\$database;" | tail -1 | tr -d '[:space:]')"
if [ "$archivelog" != "ARCHIVELOG" ]; then
  sql "$PRIMARY" "
whenever sqlerror exit failure
SHUTDOWN IMMEDIATE
STARTUP MOUNT
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
exit"
fi

echo "== 2. Primary: standby redo logs + Data Guard parameters =="
redo_bytes="$(sql "$PRIMARY" "SELECT MAX(bytes) FROM v\$log;" | tail -1 | tr -d '[:space:]')"
groups="$(sql "$PRIMARY" "SELECT COUNT(*) FROM v\$log;" | tail -1 | tr -d '[:space:]')"
srl_needed=$((groups + 1))
have_srl="$(sql "$PRIMARY" "SELECT COUNT(*) FROM v\$standby_log;" | tail -1 | tr -d '[:space:]')"
i="$have_srl"
while [ "$i" -lt "$srl_needed" ]; do
  sql "$PRIMARY" "ALTER DATABASE ADD STANDBY LOGFILE SIZE $redo_bytes;"
  i=$((i + 1))
done
sql "$PRIMARY" "
whenever sqlerror exit failure
ALTER SYSTEM SET log_archive_config='DG_CONFIG=($DB_NAME,$SB_UNIQUE)' SCOPE=BOTH;
ALTER SYSTEM SET standby_file_management=AUTO SCOPE=BOTH;
ALTER SYSTEM SET fal_server='DGSB' SCOPE=BOTH;
exit"

echo "== 3. TNS entries on both nodes (DGPRI -> primary, DGSB -> standby, DGSB_AUX -> standby by SID) =="
# DGSB_AUX must exist on BOTH nodes: with FROM ACTIVE DATABASE the primary's server
# processes push to the auxiliary using this same alias (ORA-17627/ORA-12154 otherwise).
for node in "$PRIMARY" "$STANDBY"; do
  docker exec "$node" bash -c '
    tns="$ORACLE_HOME/network/admin/tnsnames.ora"
    grep -q "^DGPRI" "$tns" 2>/dev/null || cat >> "$tns" <<EOF

DGPRI=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST='"$PRIMARY"')(PORT=1521))(CONNECT_DATA=(SERVICE_NAME='"$DB_NAME"')))
DGSB=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST='"$STANDBY"')(PORT=1521))(CONNECT_DATA=(SERVICE_NAME='"$SB_UNIQUE"')))
DGSB_AUX=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST='"$STANDBY"')(PORT=1521))(CONNECT_DATA=(SID=FREE)))
EOF'
done

echo "== 4. Standby: replace its throwaway database with an RMAN standby duplicate =="
# Same SYS password file on both sides: Data Guard authenticates redo transport with it.
tmpdir="$(mktemp -d)"
docker exec "$PRIMARY" bash -c 'cat "$(readlink -f $ORACLE_HOME/dbs/orapw$ORACLE_SID)"' > "$tmpdir/orapw"
docker exec -i "$STANDBY" bash -c 'cat > "$(readlink -f $ORACLE_HOME/dbs/orapw$ORACLE_SID)"' < "$tmpdir/orapw"
rm -rf "$tmpdir"

# RMAN active duplicate must reach the auxiliary through the LISTENER (RMAN-06217: a
# local `auxiliary /` connect is refused), and a NOMOUNT instance only registers as
# blocked — so the standby listener gets a static SID entry, and DGSB_AUX connects by SID.
docker exec "$STANDBY" bash -c 'lsn="$ORACLE_HOME/network/admin/listener.ora"
grep -q "SID_LIST_LISTENER" "$lsn" 2>/dev/null || cat >> "$lsn" <<EOF

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (SID_NAME = FREE)
      (ORACLE_HOME = $ORACLE_HOME)
    )
  )
EOF
lsnrctl reload >/dev/null'

# The aux pfile is generated FROM the standby's own full spfile: a minimal hand-written
# pfile fails NOMOUNT on 23ai/26ai Free with ORA-00443 (background process "OFSD" did
# not start). Only db_unique_name is overridden (pfile scalars: the last assignment wins).
sql "$STANDBY" "CREATE PFILE='/tmp/init_sb.ora' FROM SPFILE;"
sql "$STANDBY" "SHUTDOWN ABORT" || true
docker exec "$STANDBY" bash -c 'rm -rf /opt/oracle/oradata/FREE && mkdir -p /opt/oracle/oradata/FREE /opt/oracle/oradata/fra'
docker exec "$STANDBY" bash -c 'printf "*.db_unique_name=FREE_SB\n" >> /tmp/init_sb.ora'
sql "$STANDBY" "
whenever sqlerror exit failure
STARTUP NOMOUNT PFILE='/tmp/init_sb.ora'
exit"

echo "-- RMAN active duplicate (this copies the whole database; takes a few minutes) --"
docker exec "$STANDBY" bash -c '
rman <<EOF
connect target sys/"$ORACLE_PASSWORD"@DGPRI
connect auxiliary sys/"$ORACLE_PASSWORD"@DGSB_AUX
DUPLICATE TARGET DATABASE FOR STANDBY FROM ACTIVE DATABASE DORECOVER
  SPFILE
    SET db_unique_name='"'"'FREE_SB'"'"'
    SET fal_server='"'"'DGPRI'"'"'
    SET standby_file_management='"'"'AUTO'"'"'
    SET log_archive_config='"'"'DG_CONFIG=(FREE,FREE_SB)'"'"'
    SET log_archive_dest_2='"'"''"'"'
    SET db_recovery_file_dest='"'"'/opt/oracle/oradata/fra'"'"'
  NOFILENAMECHECK;
EOF'

echo "== 5. Silence the blocked automatic channels =="
# Oracle Free gates the whole Managed Standby feature with ORA-00439: remote transport
# (ASYNC and SYNC), FAL gap fetch, REGISTER PHYSICAL LOGFILE and MRP-fed apply — all
# verified on 23.26.2. Plain media recovery is NOT gated, so redo moves via the
# ship/ship_loop.sh cycle (copy + RECOVER AUTOMATIC FROM dir) instead; no MRP is started.
sql "$STANDBY" "ALTER SYSTEM SET fal_server='' SCOPE=BOTH;"
sql "$PRIMARY" "
ALTER SYSTEM SET log_archive_dest_2='' SCOPE=BOTH;
ALTER SYSTEM SET fal_server='' SCOPE=BOTH;"

echo "== 6. Ship + apply the archived logs so far (the shipper sidecar repeats this every 2 min) =="
PRIMARY="$PRIMARY" STANDBY="$STANDBY" ONESHOT=1 sh ship/ship_loop.sh

echo "== 7. Verify =="
echo "-- standby role/mode:"
sql "$STANDBY" "SELECT database_role, open_mode FROM v\$database;"
echo "-- last sequence APPLIED on the standby (v\$log_history reflects media recovery):"
sql "$STANDBY" "SELECT MAX(sequence#) AS standby_applied_seq FROM v\$log_history;"
echo "-- last sequence ARCHIVED on the primary:"
sql "$PRIMARY" "SELECT MAX(sequence#) AS primary_archived_seq FROM v\$archived_log;"

echo
echo "Data Guard lab ready: $PRIMARY (primary, read-write) -> $STANDBY (physical standby, MOUNTED)."
echo "Redo transport: SE-style shipping by the '*-shipper' sidecar — every 2 min it forces a"
echo "log switch, copies new archived logs and applies them with RECOVER AUTOMATIC (RPO ~ 2 min)."
echo "Oracle Free blocks live redo transport (ORA-00439), so a clean SWITCHOVER is not possible."
echo "NOTE: the standby container's healthcheck shows 'unhealthy' from now on — it is MOUNTED,"
echo "not OPEN, which is the correct standby state here."
echo "Failover / role change (run on the standby; data current to the last shipped log):"
echo "  docker stop $PRIMARY ; docker stop \$(docker ps -q -f name=-shipper)   # stop the old primary + shipper"
echo "  ALTER DATABASE ACTIVATE STANDBY DATABASE;   -- then ALTER DATABASE OPEN;"
echo "The standby needs nothing after a container restart — the shipper keeps applying."
"""


def extra_files(spec: DockerDbSpec) -> list[tuple[str, str]]:
    """Non-compose files an instance needs on disk, as ``(relpath, content)``.

    PostgreSQL HA mounts an init script into the primary to bootstrap streaming replication.
    SQL Server has no init hook and its AG spans containers, so it ships a setup script the
    provisioner runs once the nodes are healthy. Other engines/modes need none.
    """
    if spec.engine == "postgres" and spec.is_ha:
        return [("initdb/10-replication.sh", POSTGRES_HA_INITDB)]
    if spec.engine == "mssql" and spec.is_ha:
        return [("setup/setup_ag.sh", render(MSSQL_AG_SETUP, build_context(spec)))]
    if spec.engine == "oracle" and spec.is_ha:
        return [("setup/setup_dataguard.sh", render(ORACLE_DG_SETUP, build_context(spec))),
                ("ship/ship_loop.sh", ORACLE_DG_SHIP_LOOP)]
    return []


def post_start_commands(spec: DockerDbSpec) -> list[list[str]]:
    """Commands the provisioner runs (in the instance dir) once the nodes are healthy.

    SQL Server (availability group) and Oracle (Data Guard) need one: their HA cannot be
    created by compose or an image init hook, because the steps span the containers and
    must run in order."""
    if spec.engine == "mssql" and spec.is_ha:
        return [["bash", "setup/setup_ag.sh"]]
    if spec.engine == "oracle" and spec.is_ha:
        return [["bash", "setup/setup_dataguard.sh"]]
    return []


def template_path(engine: str, mode: str) -> Path:
    """Path to the compose template for (engine, mode)."""
    folder = "ha-lab" if mode == "ha-lab" else "single"
    path = TEMPLATES_DIR / engine / folder / "docker-compose.yml.j2"
    if not path.exists():
        raise FileNotFoundError(f"No docker-compose template for engine={engine} mode={mode}: {path}")
    return path


def load_template(engine: str, mode: str) -> str:
    return template_path(engine, mode).read_text(encoding="utf-8")


def build_context(spec: DockerDbSpec) -> dict[str, Any]:
    """Build the render context for a spec.

    ``DB_PASSWORD`` is intentionally NOT part of this context: the password only
    ever lands in the ``.env`` file, never in the committed compose YAML.
    """
    meta = spec.meta
    image = f"{meta.image_repo}:{spec.version}"
    ctx: dict[str, Any] = {
        "name": spec.name,
        "engine": spec.engine,
        "version": spec.version,
        "image": image,
        "host_port": spec.host_port,
        "container_port": meta.container_port,
        "username": meta.username,
        "database": meta.database,
        # A list rather than a string because the renderer has {% for %} but no {% if %}: an empty
        # list is how a template says "no bind mount" without a conditional.
        "bind_mounts": [spec.resolved_backup_mount] if spec.resolved_backup_mount else [],
        # Always set, never blank: every template pins its network so Docker's default pool cannot
        # hand this lab a range the estate already routes to a real database. See
        # models.lab_network_subnet for the two outages that made this non-optional.
        "network_subnet": spec.resolved_network_subnet,
    }
    if spec.is_ha:
        nodes = _ha_nodes(spec)
        ctx["nodes"] = nodes
        # Split lists let templates render master/slave blocks without needing
        # an {% if %} construct (the renderer only supports {{ }} and {% for %}).
        ctx["primary_nodes"] = [n for n in nodes if n["is_primary"]]
        ctx["standby_nodes"] = [n for n in nodes if not n["is_primary"]]
        # SQL Server's availability group is built by a script, not by compose, so it needs the
        # node names as shell arrays plus the names of the group and its seeded database.
        names = [n["service"] for n in nodes]
        ctx["ag_name"] = f"ag_{spec.name}"
        ctx["ag_database"] = f"{spec.name}_db"
        ctx["primary_node"] = names[0]
        ctx["node_list"] = " ".join(f'"{name}"' for name in names)
        ctx["secondary_list"] = " ".join(f'"{name}"' for name in names[1:])
        # Oracle Data Guard is strictly 1/1, so its script wants the single standby by name.
        ctx["standby_node"] = names[1] if len(names) > 1 else ""
    return ctx


def _slot_name(service_name: str) -> str:
    """Fold a service name into a legal physical replication slot name.

    PostgreSQL restricts slot names to lowercase letters, digits and underscores, so the
    dashes in ``<name>-standby-1`` have to go or ``pg_basebackup -S`` is rejected.
    """
    return "".join(
        char if (char.isalnum() and not char.isupper()) else ("_" if not char.isalnum() else char.lower())
        for char in service_name
    )


def _ha_nodes(spec: DockerDbSpec) -> list[dict[str, Any]]:
    """Per-service context rows for an HA lab compose.

    The first node is the primary (published on ``--host-port``); each standby
    is published on an incrementing port so every member is reachable on the
    single worker. ``partner_nodes`` is the repmgr/replication peer list.
    """
    names = spec.node_names()
    rows: list[dict[str, Any]] = []
    for index, node_name in enumerate(names):
        is_primary = index == 0
        rows.append(
            {
                "service": node_name,
                "role": "primary" if is_primary else "standby",
                "is_primary": is_primary,
                "host_port": spec.host_port + index,
                "node_index": index + 1,
                "partner_nodes": ",".join(names),
                "primary_host": names[0],
                # Physical replication slot this node streams through. A slot name may only
                # hold lowercase letters, digits and underscores, so the service name's dashes
                # are folded — pg_ha_01-standby-1 -> pg_ha_01_standby_1.
                "slot_name": _slot_name(node_name),
            }
        )
    return rows
