all:
  children:
    oracle_dg:
      vars:
        ansible_user: tuser
      hosts:
        orapri:
          ansible_host: 192.168.18.51
          oracle_dg_role: primary
          oracle_db_sid: dgpri
          oracle_db_unique_name: dg_primary
        orastb:
          ansible_host: 192.168.18.52
          oracle_dg_role: standby
          oracle_db_sid: dgstby
          oracle_db_unique_name: dg_standby
