all:
  children:
    oracle_rac:
      vars:
        ansible_user: tuser
      hosts:
        rac01:
          ansible_host: 192.168.18.41
          oracle_rac_number: 1
          oracle_asm_sid: +ASM1
          oracle_db_sid: pridb1
        rac02:
          ansible_host: 192.168.18.42
          oracle_rac_number: 2
          oracle_asm_sid: +ASM2
          oracle_db_sid: pridb2
