all:
  children:
    postgresql:
      vars:
        ansible_user: tuser
      hosts:
        pg-01:
          ansible_host: 192.168.18.21
          postgresql_role: primary
        pg-02:
          ansible_host: 192.168.18.22
          postgresql_role: replica
        pg-03:
          ansible_host: 192.168.18.23
          postgresql_role: replica
